<a href="https://colab.research.google.com/github/chacha86/20210227jsp/blob/master/Numpy%20%EC%82%AC%EC%9A%A9%EB%B2%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [62]:
import numpy as np

li = [1,2,3,4,5]

type(li)

arr = np.array([1,2,3,4,5])
type(arr)

li = [7,8,9,10]
tupl = (5,6,7,8)
arr2 = np.array(li)
arr3 = np.array(tupl)

arr3

# 2차원
arr4 = np.array([[1,2,3,4],
                 [5,6,7,8]])

# 3차원

arr5 = np.array([[[1,2,3,4],
                 [5,6,7,8]],
                [[1,2,3,4],
                 [5,6,7,8]] ])


arr3.shape

arr4.shape

arr5.shape

arr3.ndim
arr4.ndim
arr5.ndim

arr3.size
arr4.size
arr5.size

16

In [94]:
# 인덱싱
arr3

arr3[0]
arr3[1 : 4 : 2]


print(arr4)

arr4[0, 2]
arr4[1, 3]

arr5 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [9,10,11,12],
                 [13,14,15,16]])

arr4[:, :2]





'''
[6,7]
[10,11]
'''

'''
[1,3]
[5,7]
[13,15]
'''

arr6 = np.array([1,2,3,4,5,6,7,8,9,10])



#arr5[0:, 0:3:2]
arr6[[2, 5, 9]]

arr5[[0,1,3], 0:3:2]

arr7 = np.array([[1,2],
                 [3,4]])



arr8 = np.array([[True, False],
                 [False, True]])

arr7[arr8]

arr8 = np.array([1,2,3,4,5])



arr8
arr9 = np.array([True, False, True, False, True])

arr8[arr9]
arr8[arr8 > 3]



[[1 2 3 4]
 [5 6 7 8]]


array([4, 5])

In [113]:
# 수열로 1차원 배열 만들기
arr = np.arange(10, 21, 2)

# 랜덤하게 숫자 뽑아주는것.
arr2 = np.random.randint(-10, 10, (2,3,4))

# 삼총사
arr3 = np.zeros([3, 3,4]) # 영행렬
arr4 = np.ones([3,4]) # 1로 채움
arr5 = np.full([3,4], 4) # 특정 숫자로 채움

arr6 = np.zeros_like(arr2)

arr6



array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [141]:
# 원소 연산
np.random.seed(1)
arr1 = np.random.randint(-100, 100, (3,4))

print(arr1)

np.random.seed(100)
arr2 = np.random.randint(-100, 100, (3,4))

print(arr2)

np.random.seed(5)
arr3 = np.random.randint(-10, 10, 5)

print(arr3)
# 행렬간 연산

#최대
arr1.max()
arr2.max()
arr3.max()

# 최소
arr1.min(axis=0)
arr1.min(axis=1)

# 합
arr1.sum()
arr1.sum(axis=0)
arr1.sum(axis=1)

# 평균
arr1.mean()
arr1.mean(axis=0)
arr1.mean(axis=1)

[[-63  40 -28  37]
 [ 33 -21  92  44]
 [ 29 -29  34 -75]]
[[-92 -76 -33   3]
 [-13 -21  76  38]
 [ -6  80  -2 -47]]
[-7  4  5 -4  6]


array([ -3.5 ,  37.  , -10.25])